# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import eventex.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20160106_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='key_hash',
            field=models.CharField(default=eventex.subscriptions.models.hash_, max_length=40, verbose_name='hash'),
        ),
    ]
